# Generated by Django 2.2.2 on 2019-06-13 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.TextField()),
                ('item_price', models.IntegerField(default=0)),
                ('item_previous_price', models.IntegerField(default=0)),
                ('name', models.TextField(blank=True)),
                ('item_image', models.ImageField(blank=True, upload_to='item_image')),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.TextField()),
                ('seller_name', models.TextField(default=None, null=True)),
                ('seller_tagline', models.TextField(default=None, null=True)),
                ('seller_email', models.EmailField(default=None, max_length=254, null=True)),
                ('seller_address', models.TextField(default=None)),
                ('seller_image', models.ImageField(blank=True, upload_to='profile_image')),
                ('is_buyer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SellersItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.Items')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.Sellers')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.Sellers')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.Cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.Items'),
        ),
    ]
