# Generated by Django 2.2.2 on 2019-06-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.TextField()),
                ('seller_name', models.TextField()),
                ('seller_tagline', models.TextField()),
                ('seller_address', models.TextField(default='NULL')),
                ('seller_image', models.ImageField(blank=True, upload_to='profile_image')),
                ('is_buyer', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='SellersItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.Items')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.Sellers')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.Sellers')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.Items')),
            ],
        ),
    ]
