# Generated by Django 2.2.2 on 2019-06-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='seller_address',
            field=models.TextField(default=None),
        ),
    ]
