# Generated by Django 2.2.2 on 2019-06-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0004_auto_20190612_0504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Orders',
        ),
    ]
