# Generated by Django 2.2.2 on 2019-06-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0005_auto_20190612_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
