# Generated by Django 2.2.2 on 2019-06-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0006_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='item_image'),
        ),
    ]
