# Generated by Django 2.2.2 on 2019-06-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0007_auto_20190612_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_previous_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
