# Generated by Django 2.2.2 on 2019-06-12 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0008_auto_20190612_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersitems',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_api.Items'),
        ),
    ]
