# Generated by Django 2.2.2 on 2019-06-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0012_orders_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
