# Generated by Django 2.2.2 on 2019-06-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0014_cart_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
